### ISSUE TITLE
Preparing `beer `input from raw read count tables

### ISSUE THREAD

**Issue by FarzanehRah** [athchen/beer#3]
Hi,
I am working with phip-seq dataset and have a raw read count table that I would like to use as input for the `beer `functions. Could you please provide guidance on how to prepare the input for use with the `beer `package from a raw read count table, also steps for normalizing the data?
Thanks

**Comment by athchen** [comment]
`beer` functions start with a `PhIPData` object. Example code to construct a `PhIPData` object from a raw read count table can be found in the `PhIPData` vignette linked [here](https://www.bioconductor.org/packages/release/bioc/vignettes/PhIPData/inst/doc/PhIPData.html#creating-a-phipdata-object).

Once the data is prepared in the `PhIPData` format, data normalization and modeling are all performed with the `beer` or `edgeR` function depending on your data precision requirements (`beer` gives more accurate estimates of enrichment but may take longer depending on the number of peptides in the library. `beer` can be parallelized to run on groups of peptides (such as by viruses). `edgeR` is much faster to run on large libraries but is less accurate for detecting smaller fold-changes of enrichment.).

**Comment by FarzanehRah** [comment]
Thank you for taking the time to explain all the details!
