### ISSUE TITLE
Identifies differentially expressed peptides when each sample has several replicates

### ISSUE THREAD

**Issue by FarzanehRah** [athchen/beer#4]
Hi,
In the `beer `vignette, it's mentioned  that each sample is run individually in comparison to all beads-only samples. However, what if we have several replicates for each sample and want to obtain a single result per sample?

Additionally, I am wondering if there are any criteria for defining the groups of comparison. For example, how can we identify the beads-only samples in the metadata? Is there a specific reserved word or term that is used for this purpose?
Thank you,

**Comment by athchen** [comment]
> However, what if we have several replicates for each sample and want to obtain a single result per sample?

Currently, the `beer` method does not leverage sample replicate information (and thus cannot do a group vs group comparison). There are a few options when performing group vs beads-only samples. 
1. If you want to use the `beer` method, you can compare each sample individually to all beads-only samples, and then aggregate across replicates. 
2. The underlying model can be extended to borrow information across replicates, but this would require adjusting the source code (see the [beer paper](https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-022-08869-y) for an explanation of the model).
3. You can use `edgeR` to do a group versus beads comparison, and you can either perform this using the `beer` package (where information about the groups is contained in `group` in the colData of the PhIPData/SummarizedExperiment object; see [this link for an example](https://www.bioconductor.org/packages/release/bioc/vignettes/PhIPData/inst/doc/PhIPData.html#sample-metadata)) or by writing your own code calling the `edgeR` package. 

> For example, how can we identify the beads-only samples in the metadata? Is there a specific reserved word or term that is used for this purpose?

Samples are indicated by the `group` column in the sample metadata portion of the `PhIPData` object (see the [sample metadata section of the PhIPData vignette](https://www.bioconductor.org/packages/release/bioc/vignettes/PhIPData/inst/doc/PhIPData.html#sample-metadata)). The beads-only samples are indicated by a specific word that can be customized. To see what the current word that indicates beads-only samples, you can use `PhIPData::getBeadsName()`. To set the beads-only group indicator, you can use `PhIPData::setBeadsName()`. For more information about the beads-only indicator, type `?getBeadsName` or `?setBeadsName` in R.

**Comment by FarzanehRah** [comment]
Thank you for your response and for providing detailed guidance on how to handle this issue. Your assistance is much appreciated.
1. To perform a group versus beads-only comparison on my PhIPData object, I used the third method and ran `runEdgeR` in `beer`. The group information is stored in the "group" column of the colData, which I accessed using `phip_obj$group`. I identified the sample groups as :
`> phip_obj$group
[1] "treatment" "treatment" "beads"     "beads" `
However, the results of the analysis were not grouped as expected. Instead, the output appears to be per-sample rather than per-group:
```
                   F3             F7             H8           H9
pep_30539      7.0519203   10.26550246          NA            NA
pep_5044       7.8546080   9.44637798           NA            NA
pep_1096       9.3651240   10.69778449          NA            NA
```

2. I am not sure about the best approach to aggregate the p-values and log fold changes resulting from the `beer` method when comparing each of my samples individually to all beads-only samples. 

Another issue I am facing is with another PhIP-Seq dataset, where there is only one bead-only sample and two experimental samples. It appears that the analysis cannot be run with just one bead-only sample. is there any solutions or workarounds to address this issue?

Thanks again

**Comment by athchen** [comment]
Oops I may have been mistaken about being able to perform the group vs group with edgeR. You could easily run the group vs group comparison using edgeR code and the `PhIPData` helpers to convert the `PhIPData` object into an object used by `edgeR`. 
* To convert the PhIPData object into the object used by edgeR, you can use `as(phip_obj, "DGEList")`
* To perform the edgeR computation, you can follow the steps outlined in section 2.10 of the [edgeR manual](https://www.bioconductor.org/packages/devel/bioc/vignettes/edgeR/inst/doc/edgeRUsersGuide.pdf).

I don't think there is a clear _right_ way of doing 2, and determining and evaluating the best way for your data set is outside of the scope of what I can provide assistance on as the package maintainer. I would recommend discussing (2) with statistical collaborators if possible. 

As for the case with one-beads only sample and two experimental samples, I would note that it is not recommended to only have one beads-only sample. Since all of these methods (BEER, edgeR, etc.) provide estimates of the variances, BEER at least will not work with only one-beads only sample. 

In the case of one beads-only sample, there is no information to be learned across beads-only samples, so your best bet estimate for the negative control samples is exactly what you observe in that one sample. Thus, you'd probably only be able to do a raw fold-change comparison of each sample versus the single beads-only sample but would not have sufficient data to estimate variances or perform hypothesis testing.

**Comment by FarzanehRah** [comment]
I just wanted to express my gratitude for the insights you provided on clarification these points. Thanks!

**Comment by FarzanehRah** [comment]
Hi
 I have a follow-up question about DE analysis using `edgeR`. I performed the analysis on a group of 2 different samples and 2 bead-only controls using `exactTest`. also preformed `runEdgeR`, with _FDR < 0.05_, `runEdgeR `resulted in 27 significant hits for one sample. However, when I verified the results using `edgeR(exactTest)`, I found 196 peptides with `FDR less than 0.05` for one sample ( and 56 and 314 for the other sample respectively). 
I am unsure about how to interpret the discrepancies in the number of significant peptides obtained from the two functions. Could you please help me understand this?
Thank you

**Comment by FarzanehRah** [comment]
Another question: since the estimation of variances for bead-only requires replicates, how does BEER handle this for a single sample? Or does it calculate variances for all samples? Furthermore, if we have different types of samples, such as HIV-positive and HIV-negative, how should we set up the analysis?

**Comment by athchen** [comment]
> I am unsure about how to interpret the discrepancies in the number of significant peptides obtained from the two functions. Could you please help me understand this?

`edgeR(PhIPData)` uses dispersion estimates from the beads-only samples, then compare the each sample to the beads-only distribution using the dispersion estimates from the beads-only samples. When you test using `exactTest`, each group has an estimated dispersion which may lead to slight differences. 

> since the estimation of variances for bead-only requires replicates, how does BEER handle this for a single sample? Or does it calculate variances for all samples? 

As mentioned above, `beer` assumes that the dispersion for a given peptide in a sample is the same in the beads-only sample as it is in an actual sample. 

> Furthermore, if we have different types of samples, such as HIV-positive and HIV-negative, how should we set up the analysis?

The initial identification of hits in each sample will remain unchanged. How you choose to perform subsequent analyses comparing the results in each group is up to you.

**Comment by FarzanehRah** [comment]
Thank you for your helpful explanation. It provided valuable insights and clarified some points for me. However, I noticed that the order of the metadata in the `phip_object `was automatically changed, which led to the alteration of the bead-only samples. To address this issue, I now understand that the metadata must be ordered in the same sequence as the count table columns, which I might have missed in the documentation. Therefore, I will rerun the analysis.

![Slides](https://user-images.githubusercontent.com/51157471/229534325-2e6e5261-faef-462e-9aaf-66ecf83b4ba7.png)
