### ISSUE TITLE
Leveraging BEER for Large-scale Dataset 

### ISSUE THREAD

**Issue by FarzanehRah** [athchen/beer#5]
Hello ,

I recently performed enriched peptide analysis using edgeR, but now I would like to explore an alternative approach using the BEER package. Considering the specific requirement to identify peptides that are weakly enriched compared to seronegative samples (not bead-only samples), and taking into account the superior performance of BEER mentioned in the BEER paper in this case.

While testing the analysis with a subset of samples (1000 peptides), everything worked fine. However, when attempting to run the analysis with the complete dataset, which consists of over 300,000 peptides, I encountered an error related to parallelization:

````R
beer_out <- brew(edgeR_out, assay.names = assay_locations, BPPARAM = BiocParallel::SerialParam(stop.on.error=FALSE))

── Running JAGS
Error: BiocParallel errors
  2 remote errors, element index: 1, 2
  0 unevaluated and other errors
  first remote error:
Error in FUN(X[[i]], ...) : negative length vectors are not allowed
Execution halted
````

To address this issue and improve performance, I am considering running BEER using GPU instead of CPU. My question is whether BEER is compatible with GPU processing and if utilizing GPU could potentially resolve the aforementioned problem.

I would greatly appreciate any insights or guidance you can provide regarding the compatibility of BEER with GPU processing and its potential to address my issue effectively. 

Thank you for your time and assistance.

**Comment by athchen** [comment]
Unfortunately I do not have too much experience or insight with GPU processing. The only pointer I can give is that BEER uses `[BiocParallel](https://bioconductor.org/packages/release/bioc/html/BiocParallel.html)` to handle the parallelization. If there is a way to specify GPUs with BiocParallel then BEER is likely compatible. Hope this helps!

**Comment by FarzanehRah** [comment]
Hi,
As I mentioned earlier, I encountered an error while attempting to run `BEER` on our entire dataset (more than 300,000 peptides). However, I was able to successfully run the analysis on a subset of the data. The specific error I encountered was related to _**"BiocParallel errors"**_. To address this issue, I opened a support ticket in the `BiocParallel `package: ["BiocParallel for parallelization in BEER"](https://github.com/Bioconductor/BiocParallel/issues/256#issue-1783435566), with the invaluable assistance of [Martin](https://github.com/mtmorgan), identified that the problem lies in the data being **"too large"** for the **`rjags`** package.

Now, my question is whether there is any solution or workaround available that would allow `BEER` to handle this problem. I would greatly appreciate any guidance or suggestions you can provide.

Thank you in advance,

**Comment by athchen** [comment]
In the paper we had mentioned that because of computational limitations, the workflow may be parallelized across peptide sets, ensuring that there are sufficient peptides that are expected to not be enriched within each set. 

For example, given a library of peptides tiling proteins for various viruses, this library can be partitioned into smaller libraries by virus. To ensure that each sub library has sufficient negative controls, each sub library can include the peptides tiling proteins of the rabies virus as most people (who are still surviving) should not have antibody reactivities to rabies.

**Comment by FarzanehRah** [comment]
So, in our case where we have approximately 390,000 peptides for only one virus, does this mean that it is not possible to conduct the phip-seq analysis using BEER?

**Comment by athchen** [comment]
If you have 390,000 peptides for only one virus you can break it up in any way that makes sense, so long as there are enough peptides to estimate the null distribution for the attenuation constant (around 50%). You can use edgeR to get a guess of which peptides generally show no reactivity across your samples (and use those as your negative control peptides to estimate the null distribution), and then just randomly partition the rest into more computationally feasible subsets. 

Other candidates for negative control peptides are peptides that tile things inside the cell as those are less likely to be antibody targets.

**Comment by FarzanehRah** [comment]
Thank you for your insights and assistance.
