### ISSUE TITLE
("Running JAGS") hangs at 0%

### ISSUE THREAD

**Issue by dpschreiner** [athchen/beer#9]
this happens on both beadsRR (8 samples) and  samples (88 samples).

is there an argument to pass to get more verbose output of what's happening?

this is on a Ubuntu linux cluster - if it's a resource issue i could request more (but there is no evidence of out of memory error)

thanks in advance

**Comment by athchen** [comment]
How many peptides are in the library?

**Comment by dpschreiner** [comment]
initially 79k but i pruned out peptides with no reads and it's down to ~ 25k

**Comment by athchen** [comment]
I think for one run that's pretty large still; I presume it hangs at 0 since the model initialization may take a while. Typically when we've tested it we've used libraries of around 3000, and any parallelization is done per sample (not within a library)
